### ISSUE TITLE
znc-clientbuffer and ZNC 1.7.x-git-735-879c813

### ISSUE THREAD

**Issue by fred0r** [jpnurmi/znc-clientbuffer#13]
Hi,
wanted to try this module with a recent ZNC 1.7.x-git-735-879c813.
The Module compiled without any errors but was not visible in the webif.
I added it manually to the znc.conf, but during startup:

>Module [clientbuffer] does not support module type [Global].
>Unrecoverable config error.

**Comment by CyberShadow** [comment]
You have to add it on the network page. It is a per-network module.

**Comment by fred0r** [comment]
Oh - installed severall new znc-versions since posting this and 'all of a sudden' its there under the networks....

thx cybershadow
